name: Pabrik Video Otomatis

on:
  schedule:
    - cron: '0 5 * * *' # Berjalan otomatis setiap jam 13:00 WITA (05:00 UTC)
    - cron: '0 11 * * *' # Berjalan otomatis setiap jam 19:00 WITA (11:00 UTC)
  workflow_dispatch: # Tombol manual untuk menjalankan skrip kapan saja

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Siapkan Mesin Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Program Editing & AI
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install edge-tts requests google-generativeai
          
      - name: Produksi & Kirim Video
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot_pembuat_video.py
